Update to ORC 1.7.2
prestosql/presto-hive-apache pull request #40
Opened 2022-03-01 12:18 UTC by homar

2022-03-01 12:55 UTC, findepi commented on pom.xml
> +                                        <exclude>io/airlift/slice/**</exclude>
Should this go as an `<exclusion>`?

2022-03-01 12:55 UTC, findepi commented on pom.xml
> +                <version>3.1.1</version>
related? separate commit?

2022-03-01 12:55 UTC, findepi commented on pom.xml
> +                    <artifactId>annotations</artifactId>
Can you please document why this are excluded?

2022-03-01 12:55 UTC, findepi commented on pom.xml
> +            <version>1.7.2</version>
What version was used here before?
Does hive automatically work with newer ORC version, or is any change needed within the hive code?

We generally don't use hive code to deal with ORC, but we eg use it when creating empty bucket files.
See `io.trino.plugin.hive.HiveMetadata#createEmptyFiles`.

2022-03-02 02:17 UTC, electrum requested changes
This seems to be a copy of #11, minus the exclusion for `org.threeten:threeten-extra`, which I'm not sure is intentional or an error. That original PR was not merged because the newer ORC version is not runtime compatible with Hive.

Have you tried running the Trino tests against this version?

2022-03-02 02:21 UTC, electrum commented
The exclusion for `org.threeten:threeten-extra` is indeed needed. Without it, the library is included in the JAR, but is not relocated. It needs to be excluded entirely if not needed, excluded from relocation, or relocated.

2022-03-02 02:23 UTC, electrum commented
I just published SNAPSHOT `3.1.2-19-20220302.022206-1` if you'd like to test out Trino against this PR.

2022-03-02 15:50 UTC, homar commented on pom.xml
> +                                        <exclude>io/airlift/slice/**</exclude>
> I just published SNAPSHOT `3.1.2-19-20220302.022206-1` if you'd like to test out Trino against this PR.

Thanks, will do !

2022-03-03 12:47 UTC, homar commented
Thanks for the input Guys. This is not a way to go unfortunately

2022-03-03 12:47 UTC, closed without merging